on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install_nim"
        id: install_nim
        uses: iffy/install-nim@v3
      - run: nimble develop -y
      - name: LocalFFTW3Install
        run: nimble localinstallfftw
        env:
          LD_LIBRARY_PATH: ${PWD}/third_parth/lib
      - run: testament r tests/testall.nim
        env:
          LD_LIBRARY_PATH: ${PWD}/third_parth/lib
      - run: nimble gendoc
        env:
          LD_LIBRARY_PATH: ${PWD}/third_parth/lib
