on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install_nim"
        id: install_nim
        uses: iffy/install-nim@v3
      - run: nimble install -y
      - run: testament r tests/testall.nim
      - run: nimble gendoc
