on:
  push:
    branches:
      - master

jobs:
  gh-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "gh-pages"
      - name: "install_nim"
        id: install_nim
        uses: iffy/install-nim@v3
      - name: Set CI config github
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Fetch
        run: git fetch
      - name: Rebase
        run: git rebase -Xours origin/master
      - name: NimbleDevelop
        run: nimble develop -y
      - name: Install fftw3
        run: nimble localinstallfftw
        env:
          LD_LIBRARY_PATH: ${PWD}/third_party/lib
      - name: Gendoc
        run: nimble gendoc
        env:
          LD_LIBRARY_PATH: ${PWD}/third_party/lib
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
